server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://basededatosinguilan.postgres.database.azure.com:5432/tabla_pedidosventas
    username: davidinguilan
    password: Kamilopulistar17_
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
